Ruta absoluta kubecluster

diff --git a/kubecluster b/kubecluster
--- a/kubecluster
+++ b/kubecluster
@@ -1,6 +1,7 @@
 #!/bin/bash
 # kubecluster
 #
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 VERSION="3.3 20191011"
 PROG=`basename $0`
 SSH="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
@@ -151,7 +152,7 @@ function ip_ping() {
 	fi
 }
 function ip_ansible_ping() {
-	if ansible -i ~/ansible/inventory.all $1 -m ping &>/dev/null; then
+	if ansible -i $DIR/ansible/inventory/inventory.all $1 -m ping &>/dev/null; then
 		echo $STATUS_OK
 	else
 		echo $STATUS_ERROR
@@ -159,12 +160,12 @@ function ip_ansible_ping() {
 }
 ############################################################################################################
 function server_config(){
-	vi ansible/group_vars/all.yml
+	vi $DIR/ansible/group_vars/all.yml
 }
 
 function server_setup(){
 	ansible --version
-	ansible-playbook -l localhost ansible/server_setup.yml $@ || echo " ### ERROR ### "
+	ansible-playbook -l localhost $DIR/ansible/server_setup.yml $@ || echo " ### ERROR ### "
 }
 
 function server_init() {
@@ -270,7 +271,7 @@ function server_remove() {
 function boot_get-config() {
 	NAMES=`echo $* | tr ' ' ,`
 	[ -z "$NAMES" ] && LIMIT="" || LIMIT="--limit $NAMES"
-	ansible-playbook -i ansible/inventory/inventory.all $LIMIT ansible/get-config.yml
+	ansible-playbook -i $DIR/ansible/inventory/inventory.all $LIMIT $DIR/ansible/get-config.yml
 }
 
 function boot_edit-config() {
@@ -291,20 +292,20 @@ function boot_install() {
 	NAMES=`echo $* | tr ' ' ,`
 	[ -z "$NAMES" ] && Error "Debe indicar los nodos a instalar"
 	[ -z "$NAMES" ] && LIMIT="" || LIMIT="--limit $NAMES"
-	ansible-playbook -i ansible/inventory/inventory.discover $LIMIT ansible/boot_install.yml || Error "ERROR al ejecutar provision-install.yml"
+	ansible-playbook -i $DIR/ansible/inventory/inventory.discover $LIMIT $DIR/ansible/boot_install.yml || Error "ERROR al ejecutar provision-install.yml"
 }
 
 function boot_reinstall() {
 	NAMES=`echo $* | tr ' ' ,`
 	[ -z "$NAMES" ] && Error "Debe indicar los nodos a reinstalar"
 	[ -z "$NAMES" ] && LIMIT="" || LIMIT="--limit $NAMES"
-	ansible-playbook -i ~/ansible/inventory.installed $LIMIT ~/ansible/provision-reinstall.yml || Error "ERROR al ejecutar provision-reinstall.yml"
+	ansible-playbook -i $DIR/ansible/inventory/inventory.installed $LIMIT $DIR/ansible/provision-reinstall.yml || Error "ERROR al ejecutar provision-reinstall.yml"
 }
 function boot_reconfigure-network() {
 	NAMES=`echo $* | tr ' ' ,`
 	[ -z "$NAMES" ] && Error "Debe indicar los nodos a reconfigurar"
 	[ -z "$NAMES" ] && LIMIT="" || LIMIT="--limit $NAMES"
-	ansible-playbook -i ~/ansible/inventory.installed $LIMIT ~/ansible/reconfigure-network.yml || Error "ERROR al ejecutar reconfigure-network.yml"
+	ansible-playbook -i $DIR/ansible/inventory/inventory.installed $LIMIT $DIR/ansible/reconfigure-network.yml || Error "ERROR al ejecutar reconfigure-network.yml"
 }
 function boot_reconfigure-storage() {
         CONFIRM=false
@@ -320,7 +321,7 @@ function boot_reconfigure-storage() {
 	[ "$CONFIRM" != true ] && help_show
 	[ -z "$NAMES" ] && Error "Debe indicar los nodos a reconfigurar"
 	[ -z "$NAMES" ] && LIMIT="" || LIMIT="--limit $NAMES"
-	ansible-playbook -i ~/ansible/inventory.installed $LIMIT ~/ansible/reconfigure-storage.yml || Error "ERROR al ejecutar reconfigure-storage.yml"
+	ansible-playbook -i $DIR/ansible/inventory/inventory.installed $LIMIT $DIR/ansible/reconfigure-storage.yml || Error "ERROR al ejecutar reconfigure-storage.yml"
 }
 
 function boot_reboot() {
@@ -328,14 +329,14 @@ function boot_reboot() {
 	[ -z "$NAMES" ] && Error "Debe indicar los nombres a rearrancar"
 	[ -z "$NAMES" ] && help_show
 	LIMIT="--limit $NAMES"
-	ansible-playbook -i ansible/inventory/inventory.all $LIMIT ansible/reboot.yml
+	ansible-playbook -i $DIR/ansible/inventory/inventory.all $LIMIT $DIR/ansible/reboot.yml
 }
 
 function boot_destroy() {
 	NAMES=`echo $* | tr ' ' ,`
 	[ -z "$NAMES" ] && Error "Debe indicar los nodos a eliminar"
 	[ -z "$NAMES" ] && LIMIT="" || LIMIT="--limit $NAMES"
-	ansible-playbook -i ~/ansible/inventory.all $LIMIT ~/ansible/provision-remove.yml || Error "ERROR al ejecutar provision-remove.yml"
+	ansible-playbook -i $DIR/ansible/inventory/inventory.all $LIMIT $DIR/ansible/provision-remove.yml || Error "ERROR al ejecutar provision-remove.yml"
 }
 
 
@@ -369,12 +370,12 @@ function deploy_node-add() {
         done
         [ -z "$ROLES" ] && Error "Debe indicar por lo menos un rol"
         ROLES=${ROLES:1}
-	ansible-playbook -i ~/ansible/inventory.installed --limit $NODO -e roles=[${ROLES}] ~/ansible/deploy-node-add.yml || Error "ERROR al ejecutar deploy-node-add.yml"
+	ansible-playbook -i $DIR/ansible/inventory/inventory.installed --limit $NODO -e roles=[${ROLES}] $DIR/ansible/deploy-node-add.yml || Error "ERROR al ejecutar deploy-node-add.yml"
 }
 function deploy_node-remove() {
         NODO=$1
         [ -z "$NODO" ] && Error "Debe indicar el nodo a eliminar"
-	ansible-playbook -i ~/ansible/inventory.installed --limit $NODO ~/ansible/deploy-node-remove.yml || Error "ERROR al ejecutar deploy-node-remove.yml"
+	ansible-playbook -i $DIR/ansible/inventory/inventory.installed --limit $NODO $DIR/ansible/deploy-node-remove.yml || Error "ERROR al ejecutar deploy-node-remove.yml"
 }
 function deploy_node-list() {
 	cat ~/environment/roles.yml 2>/dev/null
@@ -414,7 +415,7 @@ function deploy_install() {
 		DEPLOY_DEPLOY=true
 	fi
 	STATUS="=========================================================================================$COLOR_END"
-        ansible-playbook -i ~/ansible/inventory.installed ~/ansible/pre-deploy.yml || Error "ERROR al ejecutar pre-deploy"
+        ansible-playbook -i $DIR/ansible/inventory/inventory.installed $DIR/ansible/pre-deploy.yml || Error "ERROR al ejecutar pre-deploy"
         deploy-save
 	#
         if [ $DEPLOY_BOOTSTRAP_SERVERS = true ] ; then
@@ -458,7 +459,7 @@ function deploy_install() {
 	exit 0
 }
 function deploy_reconfigure() {
-        ansible-playbook -i ~/ansible/inventory.installed ~/ansible/pre-deploy.yml
+        ansible-playbook -i $DIR/ansible/inventory/inventory.installed $DIR/ansible/pre-deploy.yml
         deploy-save
 	if [ $? != 0 ]; then
 		Error "ERROR al ejecutar el playbook ~/ansible/pre-deploy.yml"
@@ -477,7 +478,7 @@ function deploy_post-deploy() {
 	cinder type-create Vol_ceph
 	cinder type-key Vol_ceph set volume_backend_name="rbd-1"
         #
-	ansible-playbook -i ~/environment/multinode.yml ~/ansible/post-deploy.yml
+	ansible-playbook -i ~/environment/multinode.yml $DIR/ansible/post-deploy.yml
 	if [ $? != 0 ]; then
 		Error "ERROR al ejecutar el playbook post-deploy"
 	fi
@@ -515,7 +516,7 @@ function deploy_destroy() {
 		Error "ERROR al ejecutar kolla-ansible destroy"
 	fi
         ansible-playbook -i ~/ansible/inventory.installed ~/ansible/reconfigure-storage.yml
-	[ $REBOOT = true ] && ansible-playbook -i ~/environment/multinode.yml --limit 'all:!localhost' ~/ansible/reboot.yml
+	[ $REBOOT = true ] && ansible-playbook -i ~/environment/multinode.yml --limit 'all:!localhost' $DIR/ansible/reboot.yml
 
 	exit 0
 }
